from __future__ import annotations

from pathlib import Path

from .atomic import write_atomic_text
from .metadata import parse_readme


def rebuild_index(root: Path) -> None:
    root = Path(root)
    datasets_dir = root / "datasets"
    rows: list[str] = []
    if datasets_dir.is_dir():
        for ds in sorted(datasets_dir.iterdir()):
            readme = ds / "README.md"
            if not readme.is_file():
                continue
            fm, _ = parse_readme(readme)
            tags = ", ".join(fm.tags)
            rel = f"datasets/{fm.slug}"
            rows.append(f"| {fm.slug} | {fm.title} | {tags} | {fm.summary} | {rel} |")

    header = [
        "<!-- AUTO-GENERATED by `hub reindex`. Do not edit. -->",
        "# Data Hub Index",
        "",
        "| slug | title | tags | summary | path |",
        "|---|---|---|---|---|",
    ]
    content = "\n".join(header + rows) + "\n"
    write_atomic_text(root / "INDEX.md", content)
